//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VVE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\share\\vlog_data")]
        public string VLogDataDir {
            get {
                return ((string)(this["VLogDataDir"]));
            }
            set {
                this["VLogDataDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\share\\vlog_data\\configuratiebestanden")]
        public string VLogCfgDir {
            get {
                return ((string)(this["VLogCfgDir"]));
            }
            set {
                this["VLogCfgDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\share\\vlog_data\\kml")]
        public string KmlConfigDir {
            get {
                return ((string)(this["KmlConfigDir"]));
            }
            set {
                this["KmlConfigDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public decimal InstellingWachttijdBezettijdVerweglus {
            get {
                return ((decimal)(this["InstellingWachttijdBezettijdVerweglus"]));
            }
            set {
                this["InstellingWachttijdBezettijdVerweglus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0")]
        public decimal InstellingWachttijdBezettijdKoplus {
            get {
                return ((decimal)(this["InstellingWachttijdBezettijdKoplus"]));
            }
            set {
                this["InstellingWachttijdBezettijdKoplus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5.0")]
        public decimal InstellingWachttijdNormRijtijdVerweglus {
            get {
                return ((decimal)(this["InstellingWachttijdNormRijtijdVerweglus"]));
            }
            set {
                this["InstellingWachttijdNormRijtijdVerweglus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.0")]
        public decimal InstellingWachttijdMaxRijtijdVerweglus {
            get {
                return ((decimal)(this["InstellingWachttijdMaxRijtijdVerweglus"]));
            }
            set {
                this["InstellingWachttijdMaxRijtijdVerweglus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.0")]
        public decimal InstellingWachttijdIntrekkenAanvraag {
            get {
                return ((decimal)(this["InstellingWachttijdIntrekkenAanvraag"]));
            }
            set {
                this["InstellingWachttijdIntrekkenAanvraag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VRI {
            get {
                return ((string)(this["VRI"]));
            }
            set {
                this["VRI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long PeriodeVan {
            get {
                return ((long)(this["PeriodeVan"]));
            }
            set {
                this["PeriodeVan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long PeriodeTot {
            get {
                return ((long)(this["PeriodeTot"]));
            }
            set {
                this["PeriodeTot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dag")]
        public string VLogBestandEenheid {
            get {
                return ((string)(this["VLogBestandEenheid"]));
            }
            set {
                this["VLogBestandEenheid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int InstellingIntervalMinuten {
            get {
                return ((int)(this["InstellingIntervalMinuten"]));
            }
            set {
                this["InstellingIntervalMinuten"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public decimal InstellingTellenMinHoog {
            get {
                return ((decimal)(this["InstellingTellenMinHoog"]));
            }
            set {
                this["InstellingTellenMinHoog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InstellingTellenAlleenKoplussenCsv {
            get {
                return ((bool)(this["InstellingTellenAlleenKoplussenCsv"]));
            }
            set {
                this["InstellingTellenAlleenKoplussenCsv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CsvFilterMa {
            get {
                return ((bool)(this["CsvFilterMa"]));
            }
            set {
                this["CsvFilterMa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CsvFilterDi {
            get {
                return ((bool)(this["CsvFilterDi"]));
            }
            set {
                this["CsvFilterDi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CsvFilterWo {
            get {
                return ((bool)(this["CsvFilterWo"]));
            }
            set {
                this["CsvFilterWo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CsvFilterDo {
            get {
                return ((bool)(this["CsvFilterDo"]));
            }
            set {
                this["CsvFilterDo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CsvFilterVr {
            get {
                return ((bool)(this["CsvFilterVr"]));
            }
            set {
                this["CsvFilterVr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CsvFilterZa {
            get {
                return ((bool)(this["CsvFilterZa"]));
            }
            set {
                this["CsvFilterZa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CsvFilterZo {
            get {
                return ((bool)(this["CsvFilterZo"]));
            }
            set {
                this["CsvFilterZo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CsvFilterPer1Actief {
            get {
                return ((bool)(this["CsvFilterPer1Actief"]));
            }
            set {
                this["CsvFilterPer1Actief"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long CsvFilterPer1Van {
            get {
                return ((long)(this["CsvFilterPer1Van"]));
            }
            set {
                this["CsvFilterPer1Van"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long CsvFilterPer1Tot {
            get {
                return ((long)(this["CsvFilterPer1Tot"]));
            }
            set {
                this["CsvFilterPer1Tot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CsvFilterPer2Actief {
            get {
                return ((bool)(this["CsvFilterPer2Actief"]));
            }
            set {
                this["CsvFilterPer2Actief"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long CsvFilterPer2Van {
            get {
                return ((long)(this["CsvFilterPer2Van"]));
            }
            set {
                this["CsvFilterPer2Van"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long CsvFilterPer2Tot {
            get {
                return ((long)(this["CsvFilterPer2Tot"]));
            }
            set {
                this["CsvFilterPer2Tot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InstellingWachttijdIndivFietsersCsv {
            get {
                return ((bool)(this["InstellingWachttijdIndivFietsersCsv"]));
            }
            set {
                this["InstellingWachttijdIndivFietsersCsv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InstellingTabIndex {
            get {
                return ((int)(this["InstellingTabIndex"]));
            }
            set {
                this["InstellingTabIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://")]
        public string DpfPostUrl {
            get {
                return ((string)(this["DpfPostUrl"]));
            }
            set {
                this["DpfPostUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DpfPostUser {
            get {
                return ((string)(this["DpfPostUser"]));
            }
            set {
                this["DpfPostUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DpfPostPass {
            get {
                return ((string)(this["DpfPostPass"]));
            }
            set {
                this["DpfPostPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public decimal DpfPostMaxSizekB {
            get {
                return ((decimal)(this["DpfPostMaxSizekB"]));
            }
            set {
                this["DpfPostMaxSizekB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("alle")]
        public string DpfVriSelectie {
            get {
                return ((string)(this["DpfVriSelectie"]));
            }
            set {
                this["DpfVriSelectie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("alle")]
        public string DpfAnalyse {
            get {
                return ((string)(this["DpfAnalyse"]));
            }
            set {
                this["DpfAnalyse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DpfAutoPostEnabled {
            get {
                return ((bool)(this["DpfAutoPostEnabled"]));
            }
            set {
                this["DpfAutoPostEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tellen")]
        public string CsvAnalyse {
            get {
                return ((string)(this["CsvAnalyse"]));
            }
            set {
                this["CsvAnalyse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long DpfAutoPostDtTicks {
            get {
                return ((long)(this["DpfAutoPostDtTicks"]));
            }
            set {
                this["DpfAutoPostDtTicks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AnalyseTabIndex {
            get {
                return ((int)(this["AnalyseTabIndex"]));
            }
            set {
                this["AnalyseTabIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VLC {
            get {
                return ((string)(this["VLC"]));
            }
            set {
                this["VLC"] = value;
            }
        }
    }
}
